# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: nikhilbajaj0182@gmail.com
author_name: Pablosinyores
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: blockchain_dev_assessment

